version: '3.8'

services:
  api:
    build:
      context: ./api
      target: production
    ports:
      - '3000:3000'
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
      - /app/node_modules
    command: >
      sh -c " npm run prisma:generate && npm run prisma:migrate && npm run start:prod "

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
