version: '3.8'

services:
  api:
    build:
      context: ./api
      target: development
    ports:
      - '3000'
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
      - /app/node_modules
    command: >
      sh -c " npx prisma generate && npm run start:dev "

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
